"use client";
import { useEffect, useMemo, useState } from "react";
import type { ClinicConfig, PatientToken, PaymentRequest, QueueSummary } from "@/lib/types";

type DashboardData={date:string;config:ClinicConfig;queue:QueueSummary;tokens:PatientToken[];payments:PaymentRequest[]};
export default function DoctorDashboard(){
 const[data,setData]=useState<DashboardData|null>(null);const[settings,setSettings]=useState<ClinicConfig|null>(null);const[walkInName,setWalkInName]=useState("");const[walkInPhone,setWalkInPhone]=useState("");const[message,setMessage]=useState("");const[error,setError]=useState("");const[busy,setBusy]=useState(false);
 async function load(){const r=await fetch("/api/doctor/dashboard",{cache:"no-store"});if(r.status===401){window.location.href="/doctor/login";return;}if(!r.ok)return;const b:DashboardData=await r.json();setData(b);setSettings(prev=>prev??b.config);}
 useEffect(()=>{load();const id=window.setInterval(load,5000);return()=>window.clearInterval(id);},[]);
 async function post(url:string,payload:any){setBusy(true);setError("");setMessage("");const r=await fetch(url,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const b=await r.json();setBusy(false);if(!r.ok){setError(b.error||"Action failed.");return null;}await load();return b;}
 async function queueAction(action:string){await post("/api/doctor/queue/action",{action});}
 async function paymentAction(id:string,action:"CONFIRM"|"REJECT"){const b=await post(`/api/doctor/payments/${id}`,{action});if(b)setMessage(action==="CONFIRM"?"Payment confirmed and token(s) created.":"Payment request rejected.");}
 async function addWalkIn(e:React.FormEvent){e.preventDefault();const b=await post("/api/doctor/walkin",{patientName:walkInName,patientPhone:walkInPhone});if(b){setWalkInName("");setWalkInPhone("");setMessage(`Walk-in added as token #${b.tokenNumber}.`);}}
 async function saveSettings(e:React.FormEvent){e.preventDefault();if(!settings)return;const b=await post("/api/doctor/settings",settings);if(b){setSettings(b);setMessage("Clinic and payment settings saved.");}}
 const current=useMemo(()=>data?.tokens.find(t=>t.status==="SERVING")||null,[data]);const waiting=useMemo(()=>data?.tokens.filter(t=>t.status==="WAITING")||[],[data]);const pending=useMemo(()=>data?.payments.filter(p=>p.status==="SUBMITTED")||[],[data]);const paymentHistory=useMemo(()=>data?.payments.filter(p=>p.status!=="SUBMITTED"&&p.status!=="PENDING"&&p.status!=="PROCESSING")||[],[data]);
 if(!data||!settings)return <div className="card"><p>Loading clinic dashboard…</p></div>;
 return <div className="dashboard-stack">
 <section className="dashboard-head"><div><div className="eyebrow">{data.config.clinicName}</div><h1>Today&apos;s token queue</h1><p className="muted">{data.config.doctorName} · {data.date}</p></div><form action="/api/doctor/logout" method="post"><button className="btn btn-secondary">Logout</button></form></section>
 {(message||error)&&<div className={`alert ${error?"alert-error":"alert-success"}`}>{error||message}</div>}
 {pending.length>0&&<section className="card payment-review"><div className="card-title-row"><h2>Payments to confirm</h2><span className="count-badge">{pending.length}</span></div><p className="muted">Verify the amount and UPI reference in your UPI/bank app before confirming. Tokens are created only after confirmation.</p><div className="payment-review-list">{pending.map(p=><div className="payment-review-row" key={p.id}><div><strong>₹{p.totalAmountRupees}</strong><span>{p.patientNames.join(", ")}</span><small>{p.patientCount} token{p.patientCount>1?"s":""} · UTR: {p.utr}</small></div><div className="payment-buttons"><button className="btn btn-primary" disabled={busy} onClick={()=>paymentAction(p.id,"CONFIRM")}>Confirm payment</button><button className="btn btn-danger" disabled={busy} onClick={()=>paymentAction(p.id,"REJECT")}>Reject</button></div></div>)}</div></section>}
 <section className="doctor-grid"><div className="card current-card"><div className="card-title-row"><h2>Currently serving</h2><span className={`pill ${data.queue.paused?"pill-paused":"pill-open"}`}>{data.queue.paused?"Paused":"Live"}</span></div><div className="current-token">{current?`#${current.tokenNumber}`:"—"}</div><div className="current-name">{current?.patientName||"No patient called yet"}</div>{current?.patientPhone&&current.patientPhone!=="0000000"&&<div className="muted">{current.patientPhone}</div>}<div className="action-grid"><button className="btn btn-primary" disabled={busy||data.queue.paused} onClick={()=>queueAction("NEXT")}>{current?"Complete & call next":"Call first patient"}</button><button className="btn btn-danger" disabled={busy||!current||data.queue.paused} onClick={()=>queueAction("NO_SHOW")}>No show & next</button></div></div>
 <div className="card queue-control-card"><h2>Queue controls</h2><div className="mini-stats"><div><span>Waiting</span><strong>{data.queue.waitingCount}</strong></div><div><span>Next token</span><strong>#{data.queue.nextTokenNumber}</strong></div></div><button className={`btn btn-wide ${data.queue.bookingOpen?"btn-secondary":"btn-primary"}`} disabled={busy} onClick={()=>queueAction(data.queue.bookingOpen?"CLOSE_BOOKINGS":"OPEN_BOOKINGS")}>{data.queue.bookingOpen?"Stop new bookings":"Open bookings"}</button><button className="btn btn-secondary btn-wide" disabled={busy} onClick={()=>queueAction(data.queue.paused?"RESUME":"PAUSE")}>{data.queue.paused?"Resume queue":"Pause queue"}</button></div></section>
 <section className="doctor-grid wide-left"><div className="card"><div className="card-title-row"><h2>Waiting patients</h2><span className="count-badge">{waiting.length}</span></div>{waiting.length===0?<div className="empty">No patients are waiting.</div>:<div className="patient-list">{waiting.map(t=><div className="patient-row" key={t.id}><div className="token-circle">#{t.tokenNumber}</div><div className="patient-main"><strong>{t.patientName}</strong><span>{t.patientPhone==="0000000"?"No phone":t.patientPhone}</span></div><span className={`source source-${t.source.toLowerCase()}`}>{t.source==="WALK_IN"?"Walk-in":"Paid online"}</span></div>)}</div>}</div>
 <div className="card"><h2>Add walk-in</h2><p className="muted">Reception can add a walk-in after collecting payment/cash directly.</p><form onSubmit={addWalkIn}><label className="field"><span>Patient name</span><input required value={walkInName} onChange={e=>setWalkInName(e.target.value)} /></label><label className="field"><span>Phone (optional)</span><input inputMode="tel" value={walkInPhone} onChange={e=>setWalkInPhone(e.target.value)} /></label><button className="btn btn-primary btn-wide" disabled={busy||!data.queue.bookingOpen}>Add walk-in token</button></form></div></section>
 <section className="card settings-card"><details><summary>Clinic, UPI & token-price settings</summary><form className="settings-grid" onSubmit={saveSettings}><label className="field"><span>Clinic name</span><input value={settings.clinicName} onChange={e=>setSettings({...settings,clinicName:e.target.value})}/></label><label className="field"><span>Doctor name</span><input value={settings.doctorName} onChange={e=>setSettings({...settings,doctorName:e.target.value})}/></label><label className="field"><span>Specialization</span><input value={settings.specialization} onChange={e=>setSettings({...settings,specialization:e.target.value})}/></label><label className="field"><span>Doctor UPI ID</span><input value={settings.upiId} onChange={e=>setSettings({...settings,upiId:e.target.value})}/></label><label className="field"><span>Price per patient (₹)</span><input type="number" min="1" value={settings.tokenPriceRupees} onChange={e=>setSettings({...settings,tokenPriceRupees:Number(e.target.value)})}/></label><label className="field"><span>Start time</span><input type="time" value={settings.startTime} onChange={e=>setSettings({...settings,startTime:e.target.value})}/></label><label className="field"><span>End time</span><input type="time" value={settings.endTime} onChange={e=>setSettings({...settings,endTime:e.target.value})}/></label><label className="field"><span>Average consultation (minutes)</span><input type="number" min="1" max="60" value={settings.avgConsultationMinutes} onChange={e=>setSettings({...settings,avgConsultationMinutes:Number(e.target.value)})}/></label><label className="field"><span>Maximum tokens / day</span><input type="number" min="1" max="200" value={settings.maxTokens} onChange={e=>setSettings({...settings,maxTokens:Number(e.target.value)})}/></label><div className="settings-action"><button className="btn btn-primary" disabled={busy}>Save settings</button></div></form></details></section>
 {paymentHistory.length>0&&<section className="card"><details><summary>Payment history today ({paymentHistory.length})</summary><div className="patient-list compact-list">{paymentHistory.map(p=><div className="patient-row" key={p.id}><div className="token-circle">₹</div><div className="patient-main"><strong>₹{p.totalAmountRupees} · {p.patientNames.join(", ")}</strong><span>{p.status} {p.utr?`· ${p.utr}`:""}</span></div></div>)}</div></details></section>}
 </div>;
}
