"use client";
import { useEffect, useState } from "react";
import type { QueueSummary } from "@/lib/types";

export default function PatientQueue() {
  const [queue,setQueue]=useState<QueueSummary|null>(null); const [phone,setPhone]=useState(""); const [count,setCount]=useState(1); const [names,setNames]=useState([""]); const [error,setError]=useState(""); const [loading,setLoading]=useState(false);
  async function load(){const r=await fetch("/api/public/queue",{cache:"no-store"});if(r.ok)setQueue(await r.json());}
  useEffect(()=>{load();const id=window.setInterval(load,10000);return()=>window.clearInterval(id);},[]);
  function changeCount(value:number){const next=Math.max(1,Math.min(5,value));setCount(next);setNames(old=>Array.from({length:next},(_,i)=>old[i]||""));}
  async function book(event:React.FormEvent){event.preventDefault();setError("");setLoading(true);const response=await fetch("/api/public/payments",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({patientNames:names,patientPhone:phone})});const body=await response.json();setLoading(false);if(!response.ok){setError(body.error||"Could not start payment.");await load();return;}window.location.href=`/pay/${body.publicId}`;}
  if(!queue)return <div className="card"><p>Loading clinic queue…</p></div>; const {config}=queue; const total=count*config.tokenPriceRupees;
  return <div className="patient-layout"><section className="card patient-hero-card"><div className="eyebrow">{config.clinicName}</div><h1>{config.doctorName}</h1><p className="muted">{config.specialization}</p><div className="schedule-line">Today · {config.startTime}–{config.endTime}</div><div className="status-row"><span className={`pill ${queue.bookingOpen?"pill-open":"pill-closed"}`}>{queue.bookingOpen?"Bookings open":"Bookings closed"}</span>{queue.paused&&<span className="pill pill-paused">Queue paused</span>}</div><div className="queue-stats"><div><span>Currently serving</span><strong>{queue.currentTokenNumber?`#${queue.currentTokenNumber}`:"—"}</strong></div><div><span>Waiting</span><strong>{queue.waitingCount}</strong></div><div><span>Token fee</span><strong>₹{config.tokenPriceRupees}</strong></div></div><p className="hint">No patient account is required. Tokens are issued only after clinic staff confirms the payment.</p></section>
  <section className="card booking-card"><h2>Book today&apos;s token</h2><p className="muted">Choose how many patients you are paying for. The UPI amount is calculated automatically.</p><form onSubmit={book}><label className="field"><span>Number of patients</span><select value={count} onChange={e=>changeCount(Number(e.target.value))}>{[1,2,3,4,5].map(n=><option key={n} value={n}>{n}</option>)}</select></label>{names.map((name,i)=><label className="field" key={i}><span>Patient {i+1} name</span><input required maxLength={80} value={name} onChange={e=>setNames(old=>old.map((v,j)=>j===i?e.target.value:v))} placeholder={`Patient ${i+1} name`} /></label>)}<label className="field"><span>Contact phone number</span><input autoComplete="tel" inputMode="tel" required value={phone} onChange={e=>setPhone(e.target.value)} placeholder="9876543210" /></label><div className="payment-total"><span>Total to pay</span><strong>₹{total}</strong><small>{count} × ₹{config.tokenPriceRupees}</small></div><button className="btn btn-primary btn-wide" disabled={!queue.bookingOpen||loading}>{loading?"Preparing payment…":queue.bookingOpen?`Continue to pay ₹${total}`:"Bookings closed"}</button></form>{error&&<div className="alert alert-error">{error}</div>}</section></div>;
}
