"use client";
import { useEffect, useState } from "react";
import QRCode from "qrcode";

type Payment = { publicId:string; patientNames:string[]; patientPhone:string; patientCount:number; totalAmountRupees:number; upiId:string; status:"PENDING"|"SUBMITTED"|"PROCESSING"|"VERIFIED"|"REJECTED"; utr:string|null; tokenPublicIds:string[]; clinicName:string; doctorName:string; upiUri:string; };
export default function PaymentPage({publicId}:{publicId:string}){
  const [payment,setPayment]=useState<Payment|null>(null);const [qr,setQr]=useState("");const [utr,setUtr]=useState("");const [error,setError]=useState("");const [busy,setBusy]=useState(false);
  async function load(){const r=await fetch(`/api/public/payments/${encodeURIComponent(publicId)}`,{cache:"no-store"});if(r.ok){const p=await r.json();setPayment(p);if(p.upiUri)QRCode.toDataURL(p.upiUri,{width:280,margin:1}).then(setQr).catch(()=>setQr(""));}}
  useEffect(()=>{load();const id=window.setInterval(load,5000);return()=>window.clearInterval(id);},[publicId]);
  async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");const r=await fetch(`/api/public/payments/${encodeURIComponent(publicId)}/submit`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({utr})});const b=await r.json();setBusy(false);if(!r.ok){setError(b.error||"Could not submit payment reference.");return;}await load();}
  if(!payment)return <div className="card"><p>Loading payment…</p></div>;
  if(payment.status==="REJECTED")return <div className="token-page"><section className="card token-card"><h1>Payment not confirmed</h1><p className="muted">The clinic rejected this payment reference. Please contact the clinic or create a fresh booking.</p><a className="btn btn-primary" href="/clinic">Back to clinic</a></section></div>;
  if(payment.status==="VERIFIED")return <div className="token-page"><section className="card token-card"><div className="eyebrow">Payment confirmed</div><h1>Your token{payment.tokenPublicIds.length>1?"s":""} are ready</h1><div className="alert alert-success">₹{payment.totalAmountRupees} payment confirmed by the clinic.</div><div className="token-links">{payment.tokenPublicIds.map((id,i)=><a className="btn btn-primary btn-wide" href={`/token/${id}`} key={id}>Open {payment.patientNames[i] || `Patient ${i+1}`} token</a>)}</div></section></div>;
  return <div className="token-page"><section className="card payment-card"><div className="eyebrow">{payment.clinicName}</div><h1>Pay ₹{payment.totalAmountRupees}</h1><p className="muted">{payment.patientCount} patient{payment.patientCount>1?"s":""} · {payment.doctorName}</p>{qr&&<img className="upi-qr" src={qr} alt="UPI payment QR code" />}<div className="upi-line"><span>UPI ID</span><strong>{payment.upiId}</strong></div><a className="btn btn-primary btn-wide" href={payment.upiUri}>Open UPI app & pay ₹{payment.totalAmountRupees}</a><p className="hint">Pay the exact amount. After payment, copy the UPI transaction/reference number from your payment app.</p>{payment.status==="PENDING"?<form onSubmit={submit}><label className="field"><span>UPI transaction / UTR number</span><input required value={utr} onChange={e=>setUtr(e.target.value)} placeholder="Enter transaction reference" /></label><button className="btn btn-secondary btn-wide" disabled={busy}>{busy?"Submitting…":"I paid — submit reference"}</button></form>:<div className="alert alert-success"><strong>Payment reference submitted.</strong><br/>Waiting for clinic staff to confirm it. This page checks automatically every 5 seconds.</div>}{error&&<div className="alert alert-error">{error}</div>}</section></div>;
}
